### ISSUE TITLE
[GI-Par-02] Ajouter son enfant

### ISSUE THREAD

**Issue by SK0RPIA** [SK0RPIA/e-music-data#2]
En tant que parent
- Je peux créer un compte pour mon enfant
- Afin qu’il accède à ses propres cours
### Critères d'acceptation
- [ ] L'enfant est associé à mon compte
- [ ] Il recoit un email de confirmation de création de compte
- [ ] Il peut se connecter à son compte en tant qu'enfant
